In [23]:
import numpy as np

In [32]:
def sigmoid(inputs):
    """The sigmoid function."""
    return 1.0 / (1.0 + np.exp(-inputs))

### Initialization

In [25]:
sizes = [2, 3, 2]

num_layers = len(sizes); num_layers

3

In [26]:
sizes[1:]

[3, 2]

In [27]:
np.random.randn(3, 1)

array([[ 0.26575423],
       [-0.20766188],
       [ 0.57240696]])

In [28]:
biases = [np.random.randn(size, 1) for size in sizes[1:]]; biases

[array([[ 0.47207396],
        [ 0.35929938],
        [-0.34249691]]), array([[ 0.46635821],
        [-1.33003065]])]

In [29]:
weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]; weights

[array([[-0.49571894, -0.38090795],
        [ 0.87963153, -0.88976308],
        [ 0.97847295,  0.96390717]]),
 array([[-1.39651312, -1.00193145, -1.60983399],
        [-1.7901287 , -0.22113029,  0.00810438]])]

### Forward Pass

In [34]:
a = np.random.randn(2, 1); a 

array([[-0.33316547],
       [ 0.82207903]])

In [41]:
for b, w in zip(biases, weights):
    a = sigmoid(np.dot(w, a)+b)
print(a)

[[0.15030397]
 [0.07497412]]


In [39]:
a1 = sigmoid(np.dot(weights[0], a) + biases[0]); a1

array([[0.58757352],
       [0.609058  ],
       [0.47693657]])

In [40]:
sigmoid(np.dot(weights[1], a1) + biases[1])

array([[0.15030397],
       [0.07497412]])

In [2]:
import network
import mnist_loader

In [4]:
training_data, validation_data, test_data = mnist_loader.load_data_wrapper()

In [5]:
net = network.Network([784, 30, 10])

In [ ]:
net.SGD(training_data, 30, 10, 3.0, test_data=test_data)

Epoch 0: 8256 / 10000
Epoch 1: 9175 / 10000
Epoch 2: 9275 / 10000
Epoch 3: 9293 / 10000
Epoch 4: 9342 / 10000
Epoch 5: 9371 / 10000
Epoch 6: 9388 / 10000
Epoch 7: 9415 / 10000
Epoch 8: 9400 / 10000
Epoch 9: 9424 / 10000
Epoch 10: 9398 / 10000
Epoch 11: 9441 / 10000
Epoch 12: 9450 / 10000
Epoch 13: 9486 / 10000
Epoch 14: 9465 / 10000
Epoch 15: 9469 / 10000
Epoch 16: 9460 / 10000
Epoch 17: 9492 / 10000
Epoch 18: 9485 / 10000
Epoch 19: 9453 / 10000
Epoch 20: 9459 / 10000
Epoch 21: 9477 / 10000
Epoch 22: 9478 / 10000
Epoch 23: 9494 / 10000
