In [23]:
import numpy as np

In [32]:
def sigmoid(inputs):
    """The sigmoid function."""
    return 1.0 / (1.0 + np.exp(-inputs))

### Initialization

In [25]:
sizes = [2, 3, 2]

num_layers = len(sizes); num_layers

3

In [26]:
sizes[1:]

[3, 2]

In [27]:
np.random.randn(3, 1)

array([[ 0.26575423],
       [-0.20766188],
       [ 0.57240696]])

In [28]:
biases = [np.random.randn(size, 1) for size in sizes[1:]]; biases

[array([[ 0.47207396],
        [ 0.35929938],
        [-0.34249691]]), array([[ 0.46635821],
        [-1.33003065]])]

In [29]:
weights = [np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]; weights

[array([[-0.49571894, -0.38090795],
        [ 0.87963153, -0.88976308],
        [ 0.97847295,  0.96390717]]),
 array([[-1.39651312, -1.00193145, -1.60983399],
        [-1.7901287 , -0.22113029,  0.00810438]])]

### Forward Pass

In [34]:
a = np.random.randn(2, 1); a 

array([[-0.33316547],
       [ 0.82207903]])

In [41]:
for b, w in zip(biases, weights):
    a = sigmoid(np.dot(w, a)+b)
print(a)

[[0.15030397]
 [0.07497412]]


In [39]:
a1 = sigmoid(np.dot(weights[0], a) + biases[0]); a1

array([[0.58757352],
       [0.609058  ],
       [0.47693657]])

In [40]:
sigmoid(np.dot(weights[1], a1) + biases[1])

array([[0.15030397],
       [0.07497412]])